### ISSUE TITLE
Recovery Phrase Password

### ISSUE THREAD

**Issue by mark-hedera** [hashgraph/hedera-transaction-tool-demo#101]
### Description

During initial setup, after generating the recovery phrase, if you click cancel on the recovery phrase password box you are allowed to continue. Once inside the app, you are not able to access your recovery phrase as no password is set up.

### Steps to reproduce

1. Start initial setup of Transaction Tool
2. Generate Recovery Phrase
3. Click Cancel on Password Box
4. Click Finish to enter App
5. Select Keys -> Recovery Phrase
6. Click Confirm without entering password and confirm nothing opens.

### Hedera network

other

### Version

v0.3.0

### Operating system

macOS

**Comment by mark-hedera** [comment]
The issue also exists during the "Forgot your password" process.

**Comment by DSMatusevich** [comment]
I can reproduce it. I will issue a patch for v0.3.0

**Comment by SimiHunjan** [comment]
fixed
