### ISSUE TITLE
History Section Changes

### ISSUE THREAD

**Issue by mark-dlt** [hashgraph/hedera-transaction-tool-demo#105]
### Problem

The current history section draws attention to itself and causes confusion for users of the Transaction Tool.

- [x] Design document 

### Solution

- [x] Create a separate tab for the history section
- [ ] Link the history section to the bottom of the home page

**Comment by steven-sheehy** [comment]
Perhaps make it a collapsable pane and collapsed by default?

**Comment by SimiHunjan** [comment]
Columns: Submitting time, resign column, fee payer account, transaction type, action
action has 4 options: accepted, signed, declined, resigned
