### ISSUE TITLE
Home Screen Spacing

### ISSUE THREAD

**Issue by mark-hedera** [hashgraph/hedera-transaction-tool-demo#107]
### Problem

Items on the home screen run together preventing quick identification of separate transactions.

### Solution

Put blank spacing between all transactions/items in the list to create separation.

**Comment by DSMatusevich** [comment]
@mark-hedera could you provide a screenshot for this issue? Thanks

**Comment by mark-hedera** [comment]
In the below image both the Batch and Update Account transactions touch. When quickly scrolling through a list of transactions this lack of separation makes it hard to easily keep track of the beginning and end of each individual transaction.
![Issue](https://user-images.githubusercontent.com/65772558/151035221-537a4669-5252-4e03-b869-ff3bafbf83d0.PNG)

**Comment by DSMatusevich** [comment]
Is this more acceptable?

![Screen Shot 2022-01-26 at 10 51 17 AM](https://user-images.githubusercontent.com/42348838/151208837-729e6d0e-6dc7-4e18-84f7-7768cceed108.png)

**Comment by mark-hedera** [comment]
Yes that is perfect!
