### ISSUE TITLE
Transaction improvements

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#11]
- [x] Add an option to create a transaction from an existing transaction in the transaction creation tab
- [x] When creating a transaction, after entering the payer or a transfer row, it should show the nickname along with the account and checksum
- [x] Allow the user to modify transaction defaults
   - [x]  It lets you enter the valid start time hours, minutes, and seconds, but not nanoseconds. It should have a box for nanoseconds. When you click NOW, that box should get filled in, too. This allows the user to either fill it in with NOW (which is basically random), or fill it in with a specific number (such as zero). Which means the user can choose whether multiple transactions have the same transaction ID, or are all different.
   - [x]  Allow the user to choose which node to submit to, on the screen where the transaction is created.
   - [x]  All user to modify the max transaction fee

**Comment by DSMatusevich** [comment]
@SimiHunjan Need a bit of clarification: Currently the tool allows the user to choose the node, it just defaults to whatever you have in the Settings. Do we want to change this behavior?
![Screen Shot 2021-07-21 at 9 44 59 AM](https://user-images.githubusercontent.com/42348838/126509049-337b7996-3175-4275-b259-e8b353b1bcfc.png)

**Comment by SimiHunjan** [comment]
Good question. Since we can change the node ID there that meets the ask.
