### ISSUE TITLE
Extra dot in pop-up message

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#120]
### Description

I am not sure if we need a pop-up message after you click refresh next the account ID. After the account info request is returned the pop-up message should confirm the account was updated.

The pop-up message has an extra dot right after it displays the account ID.

### Steps to reproduce

![Screen Shot 2021-11-03 at 6 44 33 PM](https://user-images.githubusercontent.com/21989138/140243376-af9aa434-d7dd-4671-9eea-aa1fc89ad103.png)

### Additional context

Update an account using the refresh button next to account ID.

### Hedera network

testnet

### Version

0.2.0-alpha.2

### Operating system

macOS

**Comment by DSMatusevich** [comment]
Fixed the extra dot: changed it from showing the filename to just showing the base name of the file. I agree it looked weird.

I can change the behavior of the update, but that will create inconsistencies in how info files are handled. I think I would rather leave it for now.
