### ISSUE TITLE
History incorrectly states "No difference"

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#121]
### Description

The account balance changed each time I do a request because I am using the same account to pay for the query. The history window states "No difference", but when I double click on the request it highlights the balance as it did change. It should display that the balance changed between the two info requests. 

### Steps to reproduce

See above

### Additional context

![Screen Shot 2021-11-03 at 6 50 42 PM](https://user-images.githubusercontent.com/21989138/140243990-e2ce0d59-57e4-45d0-80f8-b2c89e7fa8e8.png)

![Screen Shot 2021-11-03 at 6 50 59 PM](https://user-images.githubusercontent.com/21989138/140244026-bbb48643-1768-4613-a82f-2251134d0d9e.png)

### Hedera network

testnet

### Version

0.4.0-alpha.2

**Comment by DSMatusevich** [comment]
Not a bug. I left the balance out on purpose, since there is little value in showing that it has changed (unless this is an account that has never been used, it would always change). It is easy to add if needed.

**Comment by SimiHunjan** [comment]
what if you did a transfer and got the info the see view the balance change?

I think the purpose of the table is to display any changes to the fields and we should highlight them each time even if it is the balance that is deducted from paying a transaction fee.

**Comment by DSMatusevich** [comment]
There are more efficient ways to see the balance change. As a matter of fact I would say that using a `getInfo` for the balance is a poor use of the query, since we have a free `getBalance` query. To include the balance in the history is redundant, in my opinion. That being said, adding it is no trouble. 

I think, however that we might want to discuss a "balance history" option, be it a table of available historical balances or a graph, like Hash-Hash.

**Comment by SimiHunjan** [comment]
yes, but for the purpose of getting new account info, it should display all fields that changed and not omit any fields. Otherwise, the highlighting of the balance change when you see the comparison view does not match the "No difference" text you see in the overview as the blue highlighting of the balance is letting the user know there was a change. 

sure, we can look at other options.

**Comment by lbaird** [comment]
Yes, it needs to show all changes, including balances.
