### ISSUE TITLE
Payer Account Error due to Account Nickname

### ISSUE THREAD

**Issue by mark-hedera** [hashgraph/hedera-transaction-tool-demo#129]
### Description

After entering an account number containing a nickname in the Payer account field it is updated to display the Nickname. If the field is selected again to view the account name or number and then tabbing or clicking to another field an error is displayed. The error shows states "Account format error" and requires the account info to be reentered to reset the field.

### Steps to reproduce

1. Import Account Info with Nickname
2. Click Create
3. Select any Transaction Type
4. Enter account number in the Payer account field and press enter.
5. Click within the Payer account field again
6. Press Tab or Click on another field
7. Error is displayed

### Hedera network

other

### Version

v0.3.0

### Operating system

macOS

**Comment by DSMatusevich** [comment]
fixed
