### ISSUE TITLE
"+" button for fee payer does not add new accounts

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#131]
### Description

- I click the "+" button nothing appears
- I enter an account and click the "+" button and nothing happens

### Steps to reproduce

see above

### Hedera network

other

### Version

0.4.0-alpha.3

**Comment by SimiHunjan** [comment]
The fee payer list does not drop down to show the selection of accounts in the app or a new account that  I added

**Comment by DSMatusevich** [comment]
yes, the button only opens the textbox for entering the number. Pressing <ENTER> is how we set the fee payer. However, I see how that can be confusing. I will change the behavior of the button to add the account if it is pressed.

**Comment by SimiHunjan** [comment]
The button does not even open the text box. The "+" does nothing.

**Comment by SimiHunjan** [comment]
fixed
