### ISSUE TITLE
Account update transaction resets thresholds

### ISSUE THREAD

**Issue by popowycz** [hashgraph/hedera-transaction-tool-demo#153]
### Description

When updating an existing threshold such as addition a sub-threshold, the tool zeroes out existing thresholds requiring the values be re-entered.

### Steps to reproduce

1) Launch the tool
2) Go to _Create_ tab
3) Select _Account Update_ under Transaction Type
4) Enter an account ID for which you have an account info file in the _Account to update_ field
5) Click _Modify Key_ and make a change to an existing threshold such as adding a new public key
The existing thresholds will reset across all thresholds in the key structure.

### Hedera network

mainnet

### Version

v0.3.0

### Operating system

macOS

**Comment by DSMatusevich** [comment]
This particular behavior was designed in order to push the user to set the threshold if there are changes to the key. 

I will change it to just change the threshold of the part that is modified.
