### ISSUE TITLE
Does not reset fields when creating different freeze txns

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#157]
### Description

Created a prepare upgrade transaction. That transaction did not export. Clicked the drop-down and selected freeze and upgrade. The fields were copied over from the previous selection. The fields should be blank if the user decides to change the transaction type to create.

![Screen Shot 2021-12-07 at 8 08 26 PM](https://user-images.githubusercontent.com/21989138/145146679-36e402cc-5e64-4e1d-accd-cbefdf7f0c84.png)

![Screen Shot 2021-12-07 at 8 09 03 PM](https://user-images.githubusercontent.com/21989138/145146734-9cb08053-cdca-4581-97f8-887584e55653.png)
)

### Steps to reproduce

See above.

### Hedera network

other

### Version

0.5.0-alpha.2

**Comment by SimiHunjan** [comment]
the same happens when clicking any other transaction type

**Comment by DSMatusevich** [comment]
removed the bug escape tag, since this was not part of the original design.
