### ISSUE TITLE
CSV file should include all transaction value fields

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#179]
### Problem

Currently, the CSV file allows a user to configure the sender account, submission time, node account IDs, and list of receiving accounts for a transfer transaction. 

Users should be able to set the following transaction values in the CSV file.

- Transaction memo
- Max transaction fee
- Transaction valid duration
- Fee payer

### Solution

See above.

**Comment by DSMatusevich** [comment]
@SimiHunjan @mark-hedera 

These are the changes to the CSV:

1. Added a field `Transaction Fee`: The fee must be entered in tinybars. If the field is not present, the app will use the default (backwards compatibility)
2. Added the field `Transaction Valid Duration`: an int from 1 to 180. If the field is not present, the app will use the default (backwards compatibility)
3. Added the field `Fee Payer Account`: a string of the form `XX.XX.XXXX`. If the field is not present the app will use the `Sender Account` field.
4. Added the field `Memo`: a string. If the field is not present, the app will not add a memo to the transactions
5. Removed the requirement for the CSV fields to be in order. Going forward the only requirement is that the distribution is after the common fields.
[testNewCSV.csv](https://github.com/hashgraph/hedera-transaction-tool-demo/files/7824751/testNewCSV.csv)
