### ISSUE TITLE
Add range for auto renew period

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#204]
### Problem

Users should only be able to select a value for auto renew period that is within the defined range creating a transaction.

```
ledger.autoRenewPeriod.maxDuration=8000001
ledger.autoRenewPeriod.minDuration=6999999
```

### Solution

Only allow users to select an auto renew value within the provided range.

**Comment by DSMatusevich** [comment]
There is already a range check on the app. The issue reported by Alex stems from a bug in the Account Update Transaction creation
