### ISSUE TITLE
Signing the transaction twice with same key does not add the check mark

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#216]
### Description

Sign with the key -> add signature again -> select the same key on the transaction card -> the check mark is not automatically added to the key box.

![Screen Shot 2022-01-26 at 8 13 10 PM](https://user-images.githubusercontent.com/21989138/151290697-fe579c04-2bdb-4d57-bf64-b39c0790972d.png)

### Steps to reproduce

see above

### Hedera network

other

### Version

0.7.0

**Comment by DSMatusevich** [comment]
Not a bug. As per discussions with Mark, during the requirements phase of this change, we decided that, if the user had signed and wanted to sign again we would replace disabling the key to de-emphasizing it.

**Comment by SimiHunjan** [comment]
I will follow-up on this one.

**Comment by SimiHunjan** [comment]
This issue is when the user clicks add more and adds the key again to sign
