### ISSUE TITLE
Keys can be dropped into the threshold row

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#218]
### Description

Keys can be dragged to the threshold row. The app should now allow you to do this for a row that was for the threshold value
![Screen Shot 2022-01-26 at 8 21 13 PM](https://user-images.githubusercontent.com/21989138/151291413-8fe4ed06-66cb-4a03-8d1f-a5390ace8974.png)
.

### Steps to reproduce

see above

### Hedera network

other

### Version

0.7.0

**Comment by DSMatusevich** [comment]
This is a bug, but not in the sense you think: What happened here is that the app saw a single public key and assigned the name equal to the public key. You can see that in the following bug, when trying to add a threshold.
