### ISSUE TITLE
Update error message for invalid thresholds

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#219]
### Description

Not sure if the "-" is supposed to be there in the pop-up
![Screen Shot 2022-01-26 at 8 23 20 PM](https://user-images.githubusercontent.com/21989138/151291605-1dce9ec1-265c-4794-8932-e16f3253587c.png)

### Steps to reproduce

see above

### Hedera network

other

### Version

0.7.0

**Comment by SimiHunjan** [comment]
Double click on the top-level key and a pop-up is displayed to update the threshold value. Enter the threshold value and it does not update the value.

**Comment by DSMatusevich** [comment]
This is a side-effect of the name of the key being too long. I have replaced the dash by a bullet and an unbreakable space.
