### ISSUE TITLE
Cannot set a nested threshold key value

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#220]
### Description

The third level threshold cannot be set. If you double click on it nothing pops up. If the threshold value cannot be set there should be an error message that is displayed to the user.

![Screen Shot 2022-01-26 at 8 26 13 PM](https://user-images.githubusercontent.com/21989138/151291849-0272cab3-e327-4e91-b6a4-cb3a473667a9.png)

### Steps to reproduce

see above

### Hedera network

other

### Version

0.7.0

**Comment by DSMatusevich** [comment]
There are no keys in the threshold, giving the list a size of zero. Add keys and then the threshold will be editable
