### ISSUE TITLE
Not reading the grouped account info or key files

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#221]
### Description

Added a folder of account infos and a zip of account infos to the input files folder. I don't see the new card that shows all of them.

### Steps to reproduce

see above

### Hedera network

other

### Version

0.7.0

**Comment by DSMatusevich** [comment]
@SimiHunjan can you share the zip file for testing? The app will not go into the folder structure of the zip file.

**Comment by SimiHunjan** [comment]
[info.zip](https://github.com/hashgraph/hedera-transaction-tool-demo/files/7952726/info.zip)
