### ISSUE TITLE
Keys window test plan

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#222]
### Problem

- [x] Public key can be added to the keys builder by clicking the right arrow
- [x] Account info can be added to the keys builder by clicking the right arrow
- [x] Nested threshold keys can be built by the key builder
- [x] Double-clicking on the threshold key row allows the user to change the threshold value
- [x] Double-clicking on the nested threshold key-value row allows the user to change the threshold value
- [x] If there are no keys listed under the threshold key row then user cannot modify the key value
- [ ] User can add both public keys and keys for the selected account to the existing key list
- [ ] User can add multiple public keys and account keys to the key builder. Each time a key is selected the key is added.
- [x] If user adds new keys after the threshold is selected, the user is prompted to update the threshold again
- [x] User can add multiple thresholds
- [x] User can delete keys from the key builder that were added from the public key or accounts list

### Solution

add test cases for the above

**Comment by DSMatusevich** [comment]
Items 

- [ ] User can add both public keys and keys for the selected account to the existing key list
- [ ]  User can add multiple public keys and account keys to the key builder. Each time a key is selected the key is added.

are not yet implemented. Moving them to v0.8.0
