### ISSUE TITLE
Should not be able to remove the check box in history

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#235]
### Description

View the information bundle card in history. Click on the "Replace existing nicknames" check box.

Test

- [ ] Check box cannot be modified once user performs an action on the card in history

![Screen Shot 2022-02-01 at 8 10 38 PM](https://user-images.githubusercontent.com/21989138/152091837-e8c9d051-49c8-4121-bfdd-91d870e0dccf.png)
 

### Steps to reproduce

see above

### Hedera network

other

### Version

0.7.0-alpha.2

**Comment by statop** [comment]
I believe this is already fixed?
