### ISSUE TITLE
Folder Creation Notice

### ISSUE THREAD

**Issue by mark-hedera** [hashgraph/hedera-transaction-tool-demo#24]
### Problem

When adding "shared folders", both transaction folder and email address, if required folder does not exist they are auto created upon selecting a folder or after entering a email address and pressing confirm button.

### Solution

Before creating folders add additional pop-up box displaying folders to be created and requiring confirmation of creation. If declined require new folder selection or new email address to be entered.

### Alternatives

Don't create any folders until after confirm button is pressed and confirmation is received.

**Comment by SimiHunjan** [comment]
This issue does not seem to be fixed.

**Comment by SimiHunjan** [comment]
This was complete.
