### ISSUE TITLE
Threshold for the key is incorrect

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#241]
### Description

Threshold displays 2 of 1. 2 of 1 is not possible as 1 should be the max allowable.
![Screen Shot 2022-02-01 at 8 48 11 PM](https://user-images.githubusercontent.com/21989138/152094720-d19ea1f6-d566-439e-9c81-9b55693bb1ef.png)
 

### Steps to reproduce

See above

### Hedera network

other

### Version

0.7.0-alpha.2

**Comment by SimiHunjan** [comment]
I do get the error message if I try to save it like that. But I am wondering if this should be allowed when the user actually tries to set it.

**Comment by DSMatusevich** [comment]
I seem to remember that this was done on purpose, for some reason. I think Alex wanted to be able to mark the thresholds that still needed keys, but don't quote me on that. 

I can make the change, but it is not a bug or a release blocker in my opinion.
