### ISSUE TITLE
Rename "Add Signature" to "Add more signatures"

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#242]
### Problem

Add signature confuses users when there are no new items in the to do section. Re-sign might be more intuitive for the user to understand that the transaction was already previously signed.

### Solution

See above

**Comment by statop** [comment]
Leemon agreed to "Submit more signatures"

**Comment by statop** [comment]
Final button text is "Add more signatures"
