### ISSUE TITLE
History disappears 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#278]
### Description
Clicked on the toggle to open an item in history and everything disappeared. 
![Screen Shot 2022-03-31 at 10 08 28 PM](https://user-images.githubusercontent.com/21989138/161198604-2fb0d1e9-fda4-4c83-8f18-4ae49b9e2a7b.png)

### Steps to reproduce

see above

### Hedera network

other

### Version

0.9.0-alpha.1

**Comment by SimiHunjan** [comment]
Introduced errors to settings page.

![Screen Shot 2022-03-31 at 10 10 09 PM](https://user-images.githubusercontent.com/21989138/161198762-94a5759d-a8fc-4119-a377-82ad24d7b60b.png)

**Comment by SimiHunjan** [comment]
![Screen Shot 2022-03-31 at 10 11 16 PM](https://user-images.githubusercontent.com/21989138/161198879-2ce60315-c8f6-4ef5-849c-2f94f5355410.png)

**Comment by SimiHunjan** [comment]
All tabs went blan
![Screen Shot 2022-03-31 at 10 11 52 PM](https://user-images.githubusercontent.com/21989138/161198944-73270a13-205e-4e3d-86c2-a1fc6ad771cb.png)
k

**Comment by DSMatusevich** [comment]
Fixed in V0.10.0
