### ISSUE TITLE
Update pop-up window text

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#331]
### Problem

Update the pop-up window text.

Ex:
The account update transaction succeeded. The following account properties were updated for <`accountID`>:

- Account memo
- Auto renew period
- Receiver signature required

![Screen Shot 2022-06-06 at 10 11 13 PM](https://user-images.githubusercontent.com/21989138/172301074-8aff3b39-c5cf-4c7b-9488-3d9d583187c5.png)

### Solution

see above

**Comment by DSMatusevich** [comment]
<img width="518" alt="Screen Shot 2022-06-09 at 4 02 11 PM" src="https://user-images.githubusercontent.com/42348838/172943888-16190ec0-a854-4068-b065-0c3d4fec1f50.png">
