### ISSUE TITLE
Issue with reimporting public key files

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#367]
### Description

Import a public key, delete it from Keys folder, you cannot re-import it without deleting TransactionTools/Files/.System/historyMap.json

### Steps to reproduce

See above

### Hedera network

other

### Version

v0.10.2

**Comment by statop** [comment]
This is the expected behavior. Users are not meant to do this. There really is not an easy way to fix this without a major refactor of how the history page works.

**Comment by lbaird** [comment]
So if a user accidentally deletes a public key, they will never be able to
fix it, ever?  This sounds problematic.

Is there a way to say that they are allowed to import it only if it exactly
matches the old one? That might be something that could be checked by
looking in history for where it was used, and seeing if it matches?

There needs to be some way to fix accidental deletions.
