### ISSUE TITLE
Application version can be copied to clipboard 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#38]
Currently, the text of the version cannot be copied to the clipboard. Change this so that the users can share this information easily with support.

**Comment by DSMatusevich** [comment]
@mark-hedera: Do you want copying enabled in the Settings pane or in the version popup from the front pane? Enabling copying in the Settings is easily done, but on the popup it will take more doing.

**Comment by mark-hedera** [comment]
@DSMatusevich, if a user can select the text in the settings pane and copy it, that should be acceptable.
