### ISSUE TITLE
Fee Payer Key Matching

### ISSUE THREAD

**Issue by mark-dlt** [hashgraph/hedera-transaction-tool-demo#421]
### Description

When batch CSV contains different fee payer and sender accounts, fee payer account keys are not automatically matched to the transaction.

### Steps to reproduce

Create CSV with Fee Payer and Sender Account fields. Ensure matching account info and key exist for Fee Payer and Sender Account and then open transaction tool to view missing Fee Payer account.

### Hedera network

other

### Version

v0.12.2

### Operating system

macOS

**Comment by hendrikebbers** [comment]
How can a CSV be created? Do you have a sample CSV?

**Comment by hendrikebbers** [comment]
I have some CSV files as samples but I do not know how to recreate this issue

**Comment by mark-dlt** [comment]
> I have some CSV files as samples but I do not know how to recreate this issue

You can use the below format to recreate this issue. You will need to specify different accounts for Fee Payer Account and Sender Account.

```
Fee Payer Account,0.0.0,
Sender Account,0.0.0,
Sending Time,17:00,
Node IDs,0.0.4,0.0.8
Transaction Fee,500000000,
Transaction Valid Duration,180,
Account ID,Amount per distribution (tinybar),Start Date (MM/DD/YY)
0.0.0,0,0/00/00000
```

**Comment by SimiHunjan** [comment]
![Screenshot 2023-05-05 at 1 12 08 PM](https://user-images.githubusercontent.com/21989138/236559737-677e9ece-c9fd-447a-8179-4a92fb429493.png)

I believe this one looks like it is resolved now.

**Comment by mark-dlt** [comment]
This issue still exists in v0.13.0 release
