### ISSUE TITLE
Account Update Default Values

### ISSUE THREAD

**Issue by mark-dlt** [hashgraph/hedera-transaction-tool-demo#422]
### Description

When creating an account update the default values are not populated for accounts that have been imported. This results in the account defaulting Decline Staking Rewards to false even when the account is already set to true. 

### Steps to reproduce

Import account info that has Decline Staking Rewards set to true. Create an account update in the transaction tool and then view the account on the signing page. Decline staking rewards will be listed as false.

### Hedera network

other

### Version

v0.12.2

### Operating system

macOS

**Comment by SimiHunjan** [comment]
Confirmed this issue is fixed via manual testing

**Comment by mark-dlt** [comment]
This issue still occurs when you import a transaction.

**Comment by mark-dlt** [comment]
This issue still exists in v0.13.0 release
