### ISSUE TITLE
Collation Verification

### ISSUE THREAD

**Issue by mark-dlt** [hashgraph/hedera-transaction-tool-demo#425]
### Problem

When collating the verification file is missing transaction file details, and contains non-relevant accounts, and the file name cannot be changed during collation to prevent overwriting previous results.

### Solution

1. Add the file name of the transaction that was signed as the first field within the verification file. (e.g. If the file was a batch/csv file then each transaction within the verification file should start with the same file name.)
2. Remove all accounts that are not relevant to the signed transaction and group all accounts into a single field for consistent alignment.
3. Add parameter to collate command in CLI to add a prefix to verification file (e.g. prefix.verification.csv)

**Comment by SimiHunjan** [comment]
Prioritize solution #1

**Comment by SimiHunjan** [comment]
-p or --prefix-label to add the prefix for the verification file

**Comment by SimiHunjan** [comment]
I think this is correct based on the above requirements.

Confirmed the -p param works to add a prefix to the csv file.

![Image](https://user-images.githubusercontent.com/21989138/236936419-5a229772-a1fd-4351-973a-9f1ade163702.png)

**Comment by mark-dlt** [comment]
This issue still exists in v0.13.0 release
