### ISSUE TITLE
Max Transaction Size

### ISSUE THREAD

**Issue by mark-dlt** [hashgraph/hedera-transaction-tool-demo#426]
### Problem

Currently, the CLI Collate process does not check that the final transaction size is below the max transaction size of 6,144 bytes. This can result in an invalid transaction being submitted to the network and failing.

### Solution

Once the CLI collate process has been completed and confirmed all required signers have signed the transactions, it should then check that the resulting transaction that includes signatures is below the max transaction size of 6,144 bytes. If the file size exceeds the max transaction size the collate process should fail and return an error indicating the specific transaction that exceeds the file size.

**Comment by lbaird** [comment]
In that case, the collator should include only the minimum number of
signatures needed. To minimize the size. (Yes finding the true minimum is
NP-complete, but it could use a greedy algorithm).

**Comment by mark-dlt** [comment]
This issue still exists in v0.13.0 release
