### ISSUE TITLE
macOS Ventura 13.1 Not Supported

### ISSUE THREAD

**Issue by mark-dlt** [hashgraph/hedera-transaction-tool-demo#448]
### Description

When attempting to open the Transaction Tool a message is displayed saying, "TransactionTools is damaged and can't be opened. You should move it to the Trash". This message appears to be a macOS message box and is displayed before the tool runs, as no Transaction Tool log files are created or updated. This message appears after re-installing the Transaction Tool as well.

### Steps to reproduce

Install the Transaction Tool and attempt to run the App

### Hedera network

other

### Version

v12.2

### Operating system

macOS

**Comment by SimiHunjan** [comment]
I can successfully open v0.12.3 of the application by double clicking on the icon in the Applications folder.
