### ISSUE TITLE
Sign and submit now for file update transaction not working

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#511]
### Description

Create a file update transaction
Enter all the parameters
Click on sign and submit now

It keeps saying that the time is valid (invalid submission time)
<img width="1120" alt="Screenshot 2023-09-21 at 9 18 52 PM" src="https://github.com/hashgraph/hedera-transaction-tool-demo/assets/21989138/ea5901d3-f732-4b35-99c6-c0afca993e81">

### Steps to reproduce

see above

### Hedera network

other

### Version

0.13.3-alpha

### Operating system

None

**Comment by jbair06** [comment]
Fixed in 13.3
