### ISSUE TITLE
Validate account checksum with account ID when creating a transaction

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#75]
### Problem

When creating individual transactions it's fairly easy to have a typo in either the sending or receiving account, especially as they get longer. 

### Solution

What I would see happening is adding the requirement where a sending or receiving account has to be validated with its checksum (or making it default to using checksums which could be enabled in settings).  The account and setting should be a single string entered in a single box, like 0.0.123-abcde because the user might cut and paste it with a single paste. And also because it should be entered in the same format as it is displayed. And it will be displayed as a single string with no spaces. If they don't match, the tool throws an error until they match. This could be performed for both the sender and receiver accounts.

**Comment by DSMatusevich** [comment]
![Screen Shot 2021-09-10 at 9 50 46 AM](https://user-images.githubusercontent.com/42348838/132873453-dbd809f7-dbf7-4534-975f-4dcaaeee3123.png)
![Screen Shot 2021-09-10 at 9 52 52 AM](https://user-images.githubusercontent.com/42348838/132873479-9423297e-dc64-4ceb-9c7f-3565c32405e9.png)

**Comment by DSMatusevich** [comment]
@SimiHunjan: In the case of an incorrect checksum, should I provide the user the correct one, or just leave the popup as in the screenshot?

**Comment by lbaird** [comment]
It’s ok to have a popup with the correct one. But don’t just fix the
checksum and accept the account. It should refuse to accept it until the
user types it correctly.

Also, an example is “e.g.” rather than “i.e.”, so the popup in the picture
should be corrected.

**Comment by DSMatusevich** [comment]
I knew "i.e." didn't look right! Thanks for reminding me of "e.g." 

I was planning of including the correct checksum in the popup, but the app will not correct the field. However, if the user enters just the numeric part of the account id (without the checksum) the app will assume the user doesn't know it and fill it out automatically

**Comment by lbaird** [comment]
Perfect. Thanks.
