### ISSUE TITLE
Add the memo column to CSV batch transactions

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#76]
### Problem

Currently, when creating batch transactions the CSV file does not include the transaction memo field. The transaction memo field cannot be set when creating transfer transactions from the CSV file.

### Solution

Add a memo column to the CSV file. If the memo field is available, the transactions should include the memo in the transaction memo field.

**Comment by lbaird** [comment]
Yes. Also, it should be backward compatible, so that if the file doesn’t
have that last column, then it still works (with the memo field left
empty).
