### ISSUE TITLE
Change mnemonic password incorrectly displays

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#82]
### Description

1. Change the mnemonic password
2. Enter a new password in "Password" field with 10 characters
3. Enter the same password in the "Confirm Password" field
4. Go back up and erase 3 characters in the "Password" field
5. Enter 123 to the "Password" field so it has 10 characters
6. The application should display that error message that passwords do not match. Instead, it displays the two green checkmarks when the passwords on the top and bottom are not the same.

### Steps to reproduce

See above.

### Hedera network

other

### Version

v0.3.0-alpha.1

**Comment by SimiHunjan** [comment]
Same behavior is present when changing key passwords

**Comment by DSMatusevich** [comment]
The application displays the error message if the user presses the continue button, and doesn't let the user proceed. I will change it to make the second check disappear instead
